spring:
  datasource:
    url: jdbc:postgresql://localhost:1005/citronix
    username: postgres
    password: 1005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Optional: Server configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Optional: Logging configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE